### PR TITLE
Update Pusher.com logo

### PR DESCRIPTION
**Pull request by benfoxall**
Updated pusher logo with a version from our [asset pack](https://pusher.com/about/press). While I was at it, I [optimised](https://imageoptim.com/) the other images in the post.

Thanks for the post by the way - really great read 👍

### CODE REVIEW

**Comment by cbetta** [comment]
@benfoxall thanks! I totally forgot to run the images through ImageOptim

**Comment by cbetta** [comment]
@benfoxall On that note, you should look at the signup process and see what’s going on. It got very confused.

**Comment by jbransf** [comment]
0bebb23

**Comment by jbransf** [comment]
0bebb23

**Pull request merged**
